### ISSUE TITLE
ImagePullBackOff status issue when trying to install the Kubegres operator

### ISSUE THREAD

**Issue by Gaurav-Ramakrishna** [reactive-tech/kubegres#101]
I'm trying to install the Kubegres operator by executing the `kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.15/kubegres.yaml` suggested in the [Get Started](https://www.kubegres.io/doc/getting-started.html) page.

But when I check the status by executing `kubectl get all -n kubegres-system` it shows `ImagePullBackOff` for the `pod/kubegres-controller-manager`

Any idea why I'm getting the above issue?

**Comment by alex-arica** [comment]
I tried locally and the command to install the operator worked for me: 
`kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.15/kubegres.yaml`

For `kubectl get all -n kubegres-system` I get:

```
NAME                                               READY   STATUS    RESTARTS   AGE
pod/kubegres-controller-manager-755b4c48f6-n5hfn   2/2     Running   0          4m26s

NAME                                                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/kubegres-controller-manager-metrics-service   ClusterIP   10.96.68.84   <none>        8443/TCP   4m26s

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kubegres-controller-manager   1/1     1            1           4m26s

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/kubegres-controller-manager-755b4c48f6   1         1         1       4m26s
```

Could you please try again. It could be an issue with Docker Hub at the time when you tried?

**Comment by Gaurav-Ramakrishna** [comment]
I found the issue. Had to modify the network security to allow inbound traffic on my cloud cluster instance.
Thanks
