### ISSUE TITLE
SSL certificate kubegres.io is expired

### ISSUE THREAD

**Issue by rodrigoslino** [reactive-tech/kubegres#112]
The website https://www.kubegres.io is not available on chrome

![image](https://user-images.githubusercontent.com/24231369/168926106-0e24308c-8895-4008-8665-51a826f762eb.png)

**Comment by alex-arica** [comment]
Thank you for your message.
I am investigating this issue and will let you know once it is fixed.

**Comment by joes** [comment]
Ignoring the certificate warning in the browser does not help either. All of the content of the site is gone (404 Not Found).

**Comment by alex-arica** [comment]
I would like to apologise for this issue. I am working on it right now.

We have been extremely busy working on an important platform which brings revenue to our company based in London. We could not free any resources for Kubegres until today.

I will let you know once the websites are available.

**Comment by rodrigoslino** [comment]
For people that need to look at the docs:

https://github.com/reactive-tech/kubegres-website/blob/main/website/doc/getting-started.html

**Comment by alex-arica** [comment]
https://www.kubegres.io/ is back online

**Comment by joes** [comment]
Thank you @alex-arica
