### ISSUE TITLE
Will this project be developed? 

### ISSUE THREAD

**Issue by nicraMarcin** [reactive-tech/kubegres#113]
as subject :)

**Comment by joes** [comment]
@nicraMarcin not very positive right now as the documentation/site is gone nowadays. Too bad, as I invested quite some time getting things working to my liking.

**Comment by alex-arica** [comment]
I would like to apologise for this issue. I am working on it right now. 

We have been extremely busy working on an important platform which brings revenue to our company based in London. We could not free any resources for Kubegres until today.

In regards to the future of this project, it is actively used and it is also used on the new platform that we are working, which has over 30 microservices. Each service has at least 3 instances of Postgres running with Kubegres.

An update is planned for June where we will be upgrading Kubegres with the latest code of kubebuilder v3.4.1 which is compliant with the libraries of for Kubernetes 1.23.5

I will let you know once the websites are available.

**Comment by rodrigoslino** [comment]
> @joes me too :/ I wanted to change max_connections for server but I don't rememter config structure :( and site diesn't work :( Maybe do you have example Kubegres manifest with custem postgres.conf settings?

https://github.com/reactive-tech/kubegres-website/blob/main/website/doc/getting-started.html

**Comment by alex-arica** [comment]
https://www.kubegres.io/ is back online
