### ISSUE TITLE
Cant create cluster of PostgreSql instances

### ISSUE THREAD

**Issue by artemKuznetsovDmit** [reactive-tech/kubegres#127]
Nothing happens when I apply my-postgres.yaml. If i check events in current namespace I get:

`Unable to load any deployed BackUp CronJob. 'CronJob name': backup-mypostgres - no matches for kind "CronJob" in version "batch/v1beta1"`

`kubectl api-versions | grep batch`
`batch/v1`

It seems k8s has updated and "batch/v1beta1" cant be used anymore.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by alex-arica** [comment]
Thank you.
I will release a new version of Kubegres next week in order to use the new CronJob in batch/v1

**Comment by alex-arica** [comment]
Kubegres 1.16 is available and it is compatible with Kubernetes 1.25:
https://github.com/reactive-tech/kubegres/releases/tag/v1.16
