### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Y0ngg4n** [reactive-tech/kubegres#163]
There are open CVEs, and many open issues. Also postgresql 16 is not working. It seems like this project is dead?

**Comment by behniafb** [comment]
Can someone at least give some alternatives?

**Comment by alex-arica** [comment]
A new release 

> There are open CVEs, and many open issues. Also postgresql 16 is not working. It seems like this project is dead?

Today, we are preparing a new release of Kubegres which will be available with PostgreSql 16.
This project is not dead. It is true that we are slow in responding to messages.

**Comment by alex-arica** [comment]
A new version of Kubegres is available:
https://github.com/reactive-tech/kubegres/releases/tag/v1.17
