### ISSUE TITLE
Update Kubegres installation URL from 1.16 to 1.17

### ISSUE THREAD

**Issue by behniafb** [reactive-tech/kubegres#166]
On this page:
https://www.kubegres.io/doc/getting-started.html

**Comment by alex-arica** [comment]
I see this URL on that page:
`kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.17/kubegres.yaml`

Did you refresh it ? Perhaps it was an old cache.

**Comment by behniafb** [comment]
> I see this URL on that page: `kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.17/kubegres.yaml`
> 
> Did you refresh it ? Perhaps it was an old cache.

I refreshed it now like before but it's correct now. Maybe it was an old cache. 🤷‍♂️ But it's OK now.
