### ISSUE TITLE
Wrong apiVersion in getting started examples

### ISSUE THREAD

**Issue by deorder** [reactive-tech/kubegres#2]
When I apply the example resource as is I get the following error:

```error: unable to recognize "resource.yaml": no matches for kind "Kubegres" in version "io.reactive-tech/v1"```

When I modify the apiVersion to `kubegres.reactive-tech.io/v1`, it works.

I also think the `namespace` requires an indent, so it will be inside `metadata`.

**Comment by alex-arica** [comment]
@deorder thank you for reporting this issue and @heschlie thank you for fixing it so promptly.

We made some API changes after upgrading the SDK used by Kubegres from Kubebuilder version 2 to version 3. And we forgot to update the documentations which were written before the upgrade.
