### ISSUE TITLE
Could Kubegres supports additional volumes with shared PVC?

### ISSUE THREAD

**Issue by sskurapati** [reactive-tech/kubegres#21]
We have a service that adds cert files to a mount path, how can we mount the same path to Postgres pod using Kubegres.

**Comment by alex-arica** [comment]
Hello. 
Thank you for your feature suggestion. It is a good idea.
I added it in the backlog of Kubegres. I will use this issue when committing and releasing it.

**Comment by alex-arica** [comment]
Hi,

I forgot to mention it earlier, You can specify the field "storageClassName" in your Kubegres YAML and set the name of the storage class of your choice.

Please see an example here:
https://www.kubegres.io/doc/properties-explained.html

Please let me know if that helps?

**Comment by alex-arica** [comment]
Closing this issue. Please re-open it if my answer didn't work for you.
