### ISSUE TITLE
Can kubegress use custom PV as a main storage?

### ISSUE THREAD

**Issue by mpeirone** [reactive-tech/kubegres#23]
Hi, I'd like to use GlusterFs or NFS Volume as a main storage for the database. Is it possible?

Thanks in advance

**Comment by alex-arica** [comment]
Hi, 

Yes, assuming that in your Kubernetes cluster, GlusterFs or NFS Volume are defined as storage class, it's possible.

You can specify the field "storageClassName" in your Kubegres YAML and set the name of the storage class of your choice.

Please see an example here:
https://www.kubegres.io/doc/properties-explained.html

Please let me know if you have additional questions.

**Comment by alex-arica** [comment]
Closing this issue. Please re-open it if my answer didn't work for you.
