### ISSUE TITLE
How do I delete the postgres instances?

### ISSUE THREAD

**Issue by urbany** [reactive-tech/kubegres#24]
Hi, sorry for the dumb question, but after I initialize a cluster of PostgreSql instances, how do I remove it from my k8s cluster? I deleted the statefulset, pvc, pod, etc, but there seems to be something still in my system that knows about the clsuter I'm trying to delete, because when I reaply the example YAML it says:
`kubegres.kubegres.reactive-tech.io/db unchanged`

Thanks in advance

**Comment by alex-arica** [comment]
Hi, thank you for your message.

To remove a cluster of PostgreSql instances from your K8s, you can delete the kubegres resource.

```
kubectl delete kubegres [name of resource]
```

Please let me know if that help?

**Comment by urbany** [comment]
Thank you so much, that's exactly what I wanted, I'm new to k8s, so I'0m curious, should this be obvious? If not myabe add it to the docs.
Also thank you for working on this project!

**Comment by alex-arica** [comment]
You are welcome. Thank you for your support and kind feedback.
