### ISSUE TITLE
Select Nodes for statefulsets

### ISSUE THREAD

**Issue by sshekghub** [reactive-tech/kubegres#25]
Hi, Thank you for your efforts and time to develop and manage this operator. I had a specific requirement of selecting specific nodes while creating the db cluster pods, Can I specify the nodeSelector and then key: value in the YAML of "kind :Kubegres" ?  I have created labels for nodes and would like to use those for scheduling the pods. Thanks !

**Comment by alex-arica** [comment]
Hi, thank you for your kind feedback. 
Next week, I will start working on that issue: #17 

Would that issue be similar to what you need?

**Comment by sshekghub** [comment]
Hi Alex, yes similar to issue #17. 
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - database

**Comment by alex-arica** [comment]
Perfect. What I suggest is we close this issue and you can watch the progress of the issue #17 

Thanks for your feedback.
