### ISSUE TITLE
failover - Skipping PostgreSql is already a Primary 

### ISSUE THREAD

**Issue by mpeirone** [reactive-tech/kubegres#26]
Hi, I'm trying this operator, it starts and works but as soon as the primary pod goes down, problems start:
the new primary pods run the init container, but the log is always like this:
`15/07/2021 11:31:45 - Attempting to promote a Replica PostgreSql to Primary... 
15/07/2021 11:31:45 - Skipping as this PostgreSql is already a Primary since the file '/var/lib/postgresql/data/pgdata/standby.signal' does not exist.`

So the replication user is not created and replicas stop working.

How can I solve it?

Thanks in advance

**Comment by alex-arica** [comment]
Hi, thank you for your message.
When you say "as soon as the primary pod goes down", how did it go down?
Did you delete the Pod or the StatefulSet or another way?

**Comment by mpeirone** [comment]
I tried to delete pod or disconnecting the node

**Comment by alex-arica** [comment]
Thank you.
And how many instances of Postgres was deployed?
For example 1 primary and 2 replica instances?

**Comment by mpeirone** [comment]
Yes, I can see the problem also using "Getting started" example

**Comment by alex-arica** [comment]
Thank you.
On which type of kubernetes cluster are you deploying?
For example "kind" etc...

**Comment by mpeirone** [comment]
I'm using microk8s

**Comment by alex-arica** [comment]
Thank you. I will try to reproduce this issue on my computer and let you know.

I am usually testing locally using Kind. Saying that it should work with any type of local Kubernetes cluster.

**Comment by mpeirone** [comment]
Thanks! Let me know

**Comment by mpeirone** [comment]
Have you succeded in reploducing the problem?

**Comment by alex-arica** [comment]
Sorry, I didn't have enough time to investigate it.

I will do it most likely next Friday considering my current schedule.

If it's urgent, meanwhile I suggest to try [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) as a local Kubernetes cluster. 

Once I identified the issue with microk8s, I will provide an update and a fix will follow shortly.

**Comment by alex-arica** [comment]
Hi, I installed microk8s locally. 

When I run the following command to check the available storage class:
```
microk8s kubectl get sc
```

I get:
```
No resources found
```

However, when I run the same command with [kind](https://kind.sigs.k8s.io/docs/user/quick-start/), I get:

```
NAME                     PROVISIONER             RECLAIMPOLICY 
standard (default)   rancher.io/local-path      Delete 
```

It seems like microk8s does not install a default storage class. My assumption is you need to check the microk8s documentation so that a default storage class is installed. 

Alternatively, the other option is to install a storage class in microk8s and specify it in your Kubegres YAML using the field "database.storageClassName".

Please let me know if that helps.

**Comment by alex-arica** [comment]
Closing after 8 days of inactivity.
