### ISSUE TITLE
PVC not getting bound 

### ISSUE THREAD

**Issue by sshekghub** [reactive-tech/kubegres#29]
Hi,

I have deployed the latest version and was trying to create a cluster but it is getting stuck. What is missing ? 

**PVC created is as follows**

 kubectl describe pvc postgres-db-myssodb-1-0
Name:          postgres-db-myssodb-1-0
Namespace:     aaa
StorageClass:  manual
Status:        Pending
Volume:
Labels:        app=myssodb
               index=1
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       myssodb-1-0
Events:
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  14m (x122 over 44m)   persistentvolume-controller  no volume plugin matched name: kubernetes.io/no-provisioner
  Warning  ProvisioningFailed  6m25s (x21 over 11m)  persistentvolume-controller  no volume plugin matched name: kubernetes.io/no-provisioner
  Warning  ProvisioningFailed  1s (x23 over 5m31s)   persistentvolume-controller  no volume plugin matched name: kubernetes.io/no-provisioner

**PV is as follows**
kubectl describe pv myssodb-nfs-pv
Name:            myssodb-nfs-pv
Labels:          app=myssodb
Annotations:     <none>
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Available
Claim:
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        15Gi
Node Affinity:   <none>
Message:
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    [server]
    Path:      [path]
    ReadOnly:  false
Events:        <none>

**And my kubegre yaml is as follows**

apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: myssodb
  namespace: aaa

spec:

   replicas: 2
   image: postgres:13.2
   port: 5432

   database:
      size: 15Gi
      storageClassName: manual
      volumeMount: /var/lib/postgresql/data

**Comment by alex-arica** [comment]
Hello,
Thank you for your message.
What do you see when you type?
```kubectl get sc```

**Comment by sshekghub** [comment]
kubectl get sc
NAME     PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
manual   kubernetes.io/no-provisioner   Delete          Immediate           false                  5h58m

**Comment by alex-arica** [comment]
Thank you.

It seems like the storage class that you are using doesn't ship with a provisioner.

You can also observe this in the warning message that you have kindly shared:

persistentvolume-controller no volume plugin matched name: kubernetes.io/no-provisioner

You can find some information about that type of issues here:
https://stackoverflow.com/questions/62178124/how-to-solve-k8s-persistentvolume-controller-no-volume-plugin-matched-for-kubead

This is an issue specific to a Kubernetes cluster rather than Kubegres.

**Comment by sshekghub** [comment]
ok, thank you for your reply. I will further troubleshoot this. We can close the issue for now.
