### ISSUE TITLE
Database not getting created on NFS persistent volume

### ISSUE THREAD

**Issue by sshekghub** [reactive-tech/kubegres#31]
Hi Alex,

This operator works fine when configured to use the node pv storage (hostpath), but as soon as I try to configure with nfs pv it does not work. The default database postgres is also not getting created.  I am sure my nfs server and storage have no issues as I have tried the same with postgres image (without the operator) and it works fine. All required databases were properly created in my nfs pv.  
Any idea, why it won't work with operator ? And yeah, there are absolutely no errors in the logs (controller logs, pod logs etc.) The primary pod logs show that the database is ready to accept connections, and replication pod init fails as there is nothing to replicate.  Does the operator support NFS storage ?

**Comment by alex-arica** [comment]
Thank you for your message.

Thank you.

I had a similar report from a customer, and in their case the NFS storage class didn't ship with a provisioner.

What do you observe when you run?
```
kubectl get sc
```

You can find some information about that type of issues here:
https://stackoverflow.com/questions/62178124/how-to-solve-k8s-persistentvolume-controller-no-volume-plugin-matched-for-kubead

**Comment by sshekghub** [comment]
Thank you so much for your prompt response Alex. Please find attached files for reference.
[output.docx](https://github.com/reactive-tech/kubegres/files/6975044/output.docx)
[ssdb-cluster.txt](https://github.com/reactive-tech/kubegres/files/6975049/ssdb-cluster.txt)
[ssdb-kubgres-config.txt](https://github.com/reactive-tech/kubegres/files/6975050/ssdb-kubgres-config.txt)

**Comment by sshekghub** [comment]
Hi Alex,

I created 2 pv's as initially I thought of having 1 primary and 1 replica, but later changed the config to just have 1 primary. The primary got bound to db2 and there was no db already present there for sure.

**Comment by alex-arica** [comment]
In "output.docx", for "kubectl logs ssdb-1-0 --follow", I see: 

"PostgreSQL Database directory appears to contain a database; Skipping initialization"

From where do you think the database that the message is referring to comes from?

**Comment by sshekghub** [comment]
Yes, exactly, that is what is highly confusing, and if you look at the output doc I have also pasted the NFS server directory contents which clearly indicates that it created those folders during db initialization - and probably that is what it is looking at and skipping the further initialization process ? Not sure why though. BTW, just few minutes back I deployed a STS with same pv/pvc/storageclass and everything went smoothly. The db got created successfully on NFS storage. Not sure what is happening when the same thing is done from operator....

**Comment by alex-arica** [comment]
The bit I am not sure to understand is that the storage class "nfs" that you are using does not have a provisioner ("kubernetes.io/no-provisioner") in the Kubernetes cluster. 

The behaviour of how the PV and PVC are dynamically managed is defined by a provisioner in Kubernetes. Would it be possible to install a provisioner and try again?

**Comment by sshekghub** [comment]
Hi Alex, It is working absolutely fine when I deploy just the regular statefulset yml directly (attached spec for reference
[db-nfs-storage.txt](https://github.com/reactive-tech/kubegres/files/6981665/db-nfs-storage.txt)
[db-statefulset.txt](https://github.com/reactive-tech/kubegres/files/6981668/db-statefulset.txt)
).  
The problem comes only when I am deploying using the operator so was not sure why the behaviour is different.

**Comment by alex-arica** [comment]
Ok thank you.

I am afraid I will not be able to help you with this. As I mentioned earlier, please install an external provisioner for the NFS storage class as recommended by Kubernetes doc. 

I am closing this issue as a result that it is not related to Kubegres.

**Comment by sshekghub** [comment]
No worries Alex, thank you so much for your help !
