### ISSUE TITLE
Postgres args

### ISSUE THREAD

**Issue by knusperkrone** [reactive-tech/kubegres#33]
Currently there is no way to set args for creating the database, e.g:

```yaml 
# enable logical decoding
args: ["-cwal_level=logical", "-cmax_wal_senders=1", "-cmax_replication_slots=1"]
```

**Comment by alex-arica** [comment]
Thank you for your message.

Can you pass those parameters in the postgres.conf?

There are some details about how to modify postgres.conf here:
https://www.kubegres.io/doc/override-default-configs.html

**Comment by knusperkrone** [comment]
Thanks for the quick reply.

Works like a charm!
