### ISSUE TITLE
How to recover from a full disk

### ISSUE THREAD

**Issue by tgates-nalej** [reactive-tech/kubegres#38]
In the real world, there is always a risk of exceeding available storage.  I ran the `getting started` configuration, and then ran the following test case to exceed the default storage of 200Mi.  The PODs kept crashing.  I tired to increase the storage space in the CR, but it didn't work.  What is the proper procedure to recover this real work scenario?   

```
CREATE DATABASE tgates_test_db1;

\c tgates_test_db1

CREATE TABLE scale_data (
section NUMERIC NOT NULL,
id1     NUMERIC NOT NULL,
id2     NUMERIC NOT NULL
);

INSERT INTO scale_data
SELECT sections.*, gen.*, CEIL(RANDOM()*100)
FROM GENERATE_SERIES(1, 300)     sections,
     GENERATE_SERIES(1, 900000) gen
WHERE gen <= sections * 3000;
```

**Comment by alex-arica** [comment]
Thank you. There is an issue #34 which was reported from a user with a similar issue.

It seems like expanding the storage does not work as expected in all use-cases.

I am going to work on this potential bug fix next.

I am closing this issue and you can follow an update by watching #34

**Comment by alex-arica** [comment]
I committed a potential bug fix in master.

To test it, please run the following command in your Kubernetes cluster:

```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

Could you please help me by testing it and let me know if you are happy with it?

Once you confirmed it is working for you, I will create a new tag 1.10

Please let me know and thanks in advance for your help!
