### ISSUE TITLE
kubegres-controller-manager keeps restarting but there's no error in container log

### ISSUE THREAD

**Issue by edwardzjl** [reactive-tech/kubegres#43]
I'm new to kubegres, so this might probably be a miss-configuration or sth.

After I setup a cluster following the [getting-started](https://www.kubegres.io/doc/getting-started.html) tutorial, the `kubegres-controller-manager` pod keeps restarting, while the postgres instance pods seems running ok:

![image](https://user-images.githubusercontent.com/7287580/134290531-f40013c9-dfa4-4729-b706-b25610731e30.png)

I checked the log of two containers running inside `kubegres-controller-manager` pod, neither of them contains error:

`manager` container:
![image](https://user-images.githubusercontent.com/7287580/134290764-9a525e5a-a79d-4332-9c1a-1ffbd9d3f781.png)

`kube-rbac-proxy` container:
![image](https://user-images.githubusercontent.com/7287580/134290838-3f76c6a5-7b0b-49b3-848a-a2ace209c93b.png)

But the postgres cluster and service are all running well, I can access the database with no problem. (I port-forward the postgres service to access the db)

I'm not sure what's going on, please help me get the `kubegres-controller-manager` working

**Comment by ylck** [comment]
Try  `kubectl logs <pod-name> -n kubegres-system --previous`  
`--previous` will show you logs of the previous instantiation of a container

Then try `kubectl describe <pod-name> -n kubegres-system`
check "state reason","last state reason" and "Events"

**Comment by edwardzjl** [comment]
I observed an "OOMKilled" status just before the pod become "CrashLoopBackOff". I expand the resources limit to 64Mi of memory (used to be 30Mi) and the controller seems to work properly now. So why the default config does not work on my cluster? Should we just expand it to a larger number?

**Comment by alex-arica** [comment]
Thank you for highlighting the memory issue that you are having. I am going to use this issue to investigate why this is happening and eventually increase the memory limit as suggested. We have not had any issue in prod so not sure why you are having this issue.

**Comment by edwardzjl** [comment]
@alex-arica Thanks for your quick reply. I will keep 64mb limit for my cluster as it's working and looking forward to any updates.

**Comment by alex-arica** [comment]
I am pleased to announce the release of Kubegres 1.10 which includes the increase of Kubegres controller's memory limit from 30Mi to 60Mi.
https://github.com/reactive-tech/kubegres/releases/tag/v1.10

Thanks to @edwardzjl for suggesting this feature.

To install Kubegres 1.10, please run:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.10/kubegres.yaml
```

**Comment by antoinetran** [comment]
Thanks for fixing this issue. We reproduced this issue in a on-premise cluster (10 nodes) but not on cloud cluster (5 node). The cloud cluster has very small CPU/RAM in total ocmpared to on-premise cluster. I guess the number of nodes has a role in the crash? We could not get any info from logs of the manager too.

**Comment by alex-arica** [comment]
Thank you for your message. We have not identified the root cause of this issue. I could not reproduce it in our clusters.

Please let me know if after the upgrade you still encounter this issue.
