### ISSUE TITLE
Kubegres manager fails to start on local minikube

### ISSUE THREAD

**Issue by leonz** [reactive-tech/kubegres#50]
Hi!  I am trying to run Kubegres on my Minikube instance (applying the default resource yaml) but it is failing to start with:

```2021-10-05T19:45:11.477Z	ERROR	setup	unable to start manager	{"error": "Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"}```

My kubernetes service:
```
[~] $ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   58m
```

Is there something else I need to configure that might be missing?

**Comment by alex-arica** [comment]
Thank you for your message.

I will run Kubegres on Minikube tomorrow morning (UK time) and let you know. Last time I tried it was working.

**Comment by leonz** [comment]
I was able to confirm that this was not only affecting kubegres, but also kube-proxy and the storage-provisioner:
```
[~] $ k get pods -A
NAMESPACE                   NAME                                           READY   STATUS             RESTARTS   AGE
kube-system                 coredns-f9fd979d6-9l2p8                        0/1     Running            0          116m
kube-system                 etcd-minikube                                  1/1     Running            0          116m
kube-system                 kube-apiserver-minikube                        1/1     Running            0          116m
kube-system                 kube-controller-manager-minikube               1/1     Running            0          116m
kube-system                 kube-proxy-w6xp8                               0/1     CrashLoopBackOff   19         116m
kube-system                 kube-scheduler-minikube                        1/1     Running            0          116m
kube-system                 storage-provisioner                            0/1     CrashLoopBackOff   18         116m
```

I don't believe this is specific to this repository.  Here's an issue that seems to match: https://github.com/kubernetes/minikube/issues/11513

The fix:

1. Make this modification to the `kube-proxy` configmap:

```
$ k edit configmap -n kube-system kube-proxy
----
...
  6 data:
  7   config.conf: |-
...
 19     conntrack:
 20       maxPerCore: 0 # was "null"
```

2. Delete the kube-proxy and storage-provisioner pods:

```kubectl -n kube-system delete pod kube-proxy-w6xp8 storage-provisioner```


Once they restart and run successfully, Kubegres was able to start correctly.

**Comment by alex-arica** [comment]
Excellent, I am glad that it worked for you. Thank you for the details that you have provided, they could be useful if others face similar issues.

In case of, I deployed Kubegres on Minikube v1.23.0 on Debian Bullseye, and it worked for me without any manual changes.
