### ISSUE TITLE
How to fix replica not sync in kubegres

### ISSUE THREAD

**Issue by simsicon** [reactive-tech/kubegres#59]
Hi, I found this fatal error in kubegres replica:

> FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000003000000A400000063 has already been removed

I think I need to run `pg_basebackup` to reset the cluster, but I am wondering how that action should be performed with kubegres?

Thanks

**Comment by alex-arica** [comment]
I made a new change to Kubegres so that it detects this type of issue and replace Replicas with unhealthy replication state. This will work as long as the official Postgres binary `pg_isready` reports as unhealthy.

To install Kubegres 1.13, please run:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.13/kubegres.yaml
```

**Comment by simsicon** [comment]
> I made a new change to Kubegres so that it detects this type of issue and replace Replicas with unhealthy replication state. This will work as long as the official Postgres binary `pg_isready` reports as unhealthy.
> 
> To install Kubegres 1.13, please run:
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.13/kubegres.yaml
> ```

Great, Thank you, by the way after applied the new parameter you suggested, I haven't meet the issue yet.
