### ISSUE TITLE
Improve the failover process for Replica

### ISSUE THREAD

**Issue by JuliuszJ** [reactive-tech/kubegres#60]
Hi Alex, many thanks for your amazing work with Kubegres. I tried to test crash of secondary Postgres. I conducted 2 separate tests. In 1st test I scaled down STS of secondary Postgres to zero. In second test I stopped k3d node on which that STS is running. Unfortunately in both test nothing happened. It would be great if Kubegres will run new instance of secondary Postgres in that case to achieve desired state. Regards, Juliusz.

**Comment by alex-arica** [comment]
@JuliuszJ I released a "beta" version in the main branch which fix the issue that you reported. To install it and test it please run: 
```
kubectl apply -f  https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

Please let me know if it works for you. Once you confirmed it, I will release a new version of Kubegres.

**Comment by alex-arica** [comment]
@JuliuszJ Do you think you could help by testing this change today? I am planning to release it Wednesday.

All you have to do is to conduct the 2 tests that you mentioned in your initial message when you created this issue.

I released a "beta" version in the main branch which fix the issue that you reported. To install it and test it please run: 
```
kubectl apply -f  https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

Please let me know if it works for you. Once you confirmed it, I will release a new version of Kubegres.

**Comment by JuliuszJ** [comment]
@alex-arica @ylck I ran both tests and they finished successfully. Thank you very much! However after test with stopping of k3d node I noticed something strange. After execution of command:
`kubectl exec -it my-kubegres-instance-6-0 -- /bin/bash`
i got message:
`Defaulted container "my-kubegres-instance-6" out of: my-kubegres-instance-6, setup-replica-data-directory (init)`
It seems that sidecar (init) container `setup-replica-data-directory` is still running. It was not happened when I scaled STS to 0.

**Comment by alex-arica** [comment]
Thank you for checking. 
What do you see in the logs of that pod?

**Comment by JuliuszJ** [comment]
on new primary:
`02/11/2021 10:03:11 - Attempting to promote a Replica PostgreSql to Primary...
02/11/2021 10:03:11 - Promoting by creating the promotion trigger file: '/data/pgdata/promote_replica_to_primary.log'`
on new secondary:
`02/11/2021 10:04:24 - Attempting to copy Primary DB to Replica DB...
ls: cannot access '/data/pgdata': No such file or directory
02/11/2021 10:04:24 - Copying Primary DB to Replica DB folder: /data/pgdata
02/11/2021 10:04:24 - Running: pg_basebackup -R -h rbd-citus-coord -D /data/pgdata -P -U replication;
waiting for checkpoint
    0/27542 kB (0%), 0/1 tablespace
11683/27542 kB (42%), 0/1 tablespace
27552/27552 kB (100%), 0/1 tablespace
27552/27552 kB (100%), 1/1 tablespace
02/11/2021 10:04:24 - Copy completed
`
It seems init containers finished their job.

**Comment by alex-arica** [comment]
Thank you. Yes it managed to copy it's data from primary.

Is there anything else in the logs saying that that replica pod is streaming data from primary pod?

**Comment by alex-arica** [comment]
Are you able to connect to that replica and run SQL queries?

And is there anything else in the logs saying that that replica pod is streaming data from primary pod?

**Comment by JuliuszJ** [comment]
> Are you able to connect to that replica and run SQL queries?

yes
> And is there anything else in the logs saying that that replica pod is streaming data from primary pod?

Just I am away from my test environment and I can not check the logs. However after my my tests I checked the replication by  creation of a table on primary DB and which was successfully replicated to secondary DB.

**Comment by alex-arica** [comment]
Thank you for your kind help with testing. If the init container keeps hanging, we can open a new issue about it and I will investigate it.

I will release a new version of Kubegres this evening London time.

**Comment by JuliuszJ** [comment]
Thank you very much for quick fix.

**Comment by alex-arica** [comment]
Kubegres version 1.13 is available with the changes that we discussed about in this issue. 

Please see the release page: 
https://github.com/reactive-tech/kubegres/releases/tag/v1.13

Thank you @JuliuszJ for your help!

I am closing this issue.
