### ISSUE TITLE
New Statefulset is created during every node start EKS

### ISSUE THREAD

**Issue by Premfer** [reactive-tech/kubegres#68]
Hi ,

we are hosting postgres in cluster using kubegres, and sometimes in on prem and all the time in eks when ever node is restarted or cluster is scaled down, when it is up new statefulsets are created rather than using the existing ones. This is causing many redundant ebs volumes getting created , since dev clusters will be scaled down in night times daily the number of statefulset and number of EBS volume is very high.

Kindly advice what can be done to avoid this.

Thanks

**Comment by alex-arica** [comment]
Thank you for your message. 

For that type of situation when there is a maintenance of a Kubernetes cluster, we switch off the failover feature prior to a node restart.

It is a manual process, so you have to disable the failover feature for your cluster of Postgres. Please see the field failover in this page which explains how to do so:
https://www.kubegres.io/doc/properties-explained.html

Please let me know if that helps.

**Comment by alex-arica** [comment]
HI @Premfer  could you please close this issue if my message helped you?
Otherwise, please feel free to add more comments.

**Comment by Premfer** [comment]
Hi @alex-arica  sorry for the delayed response yes it worked. Thanks.
