### ISSUE TITLE
Does Kubegres work on Openshift?

### ISSUE THREAD

**Issue by gorantornqvist** [reactive-tech/kubegres#70]
Cant see any info in the docs...guess I will have to try :)

**Comment by alex-arica** [comment]
Even if I have not personnally tested Kubegres on Openshift, it should work because Openshift runs on the Red Hat enterprise Linux operating system and Kubernetes. 

On the IBM website they [wrote](https://www.ibm.com/cloud/blog/openshift-vs-kubernetes):

> The central differentiating feature between the two platforms is that the OpenShift container platform includes Kubernetes’ platform and features (as well as Docker features). But Kubernetes does not include OpenShift services, and it is its own standalone option, with its own unique Kubernetes dashboard.
> 
> Moreover, though both are open-source programs, OpenShift is a paid platform service from Red Hat, while Kubernetes open-source code is a free service that can be downloaded from GitHub. 
>

**Comment by gorantornqvist** [comment]
Hi, I can confirm that Kubegres works fine on openshift...:)

**Comment by alex-arica** [comment]
Thank you for confirming.
