### ISSUE TITLE
Database size can not be updated

### ISSUE THREAD

**Issue by simsicon** [reactive-tech/kubegres#79]
HI, I have initially created a pg cluster with 500GB spec, then I manually resized the PVCs to 800GB, which works fine, and also I tried to override the config as 
```
...
database:
      size: 800Gi
```
But the new created nodes remain the size of 500GB if the old ones were deleted, seems the override not working?

Thanks

**Comment by alex-arica** [comment]
Thank you for your message.

Kubegres doesn't allow resizing because Kubernetes' StatefulSet doesn't support it yet. 
This feature is in the roadmap: #49

**Comment by simsicon** [comment]
Thanks for the quick reply, would love to see the upstream supports coming.

**Comment by alex-arica** [comment]
Yes I am looking forward to this feature too! Fingers crossed the Kubernetes community will release it at the beginning of 2022. Once it's available, it will be implemented in Kubegres as soon as possible.

If it's ok with you, I am closing this ticket, as it will be handled with #49
