### ISSUE TITLE
How to create creating a custom user and a database by overriding primary_init_script.sh

### ISSUE THREAD

**Issue by t-kataym** [reactive-tech/kubegres#8]
I'm trying to override primary_init_script.sh in order to create creating a custom user and a database.

Based on the [tutorial](https://www.kubegres.io/doc/getting-started.html), it works file (3 Pods are created and "postgres" database are accessible by "postgres" user).

However if I modified yaml files for creating the user "user1" with password "user1Psw" and database "testdb", it does not affect. Database "postgres" and user "postgres" exist, but "user1" and "testdb" are not created.

Procedure:
1. Recreate Kube cluster
1. ```$ kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.1/kubegres.yaml```
1. ```$ kubectl apply -f my-postgres-secret.yaml```
1. ```$ kubectl apply -f my-postgres-config.yaml```
1. ```$ kubectl apply -f my-postgres.yaml```
1. ```$ kubectl exec -it mypostgres-1-0 -- /bin/bash```
1. ```# psql -l -U postgres```  -> return 3 databases "postgres", "template0" and "template1" 

I attached yaml files. 
The modification of yaml files is based on [the site](https://www.kubegres.io/doc/set-config-map.html):
* postgres-secret.yaml  
Append ```stringData.myDbUserPassword: user1Psw```.
*  my-postgres-config.yaml  
Newly created using [Example](https://www.kubegres.io/doc/set-config-map.html#primary_init_script).  Then changed followings:
```namespace: default```
```customDatabaseName="testdb"```
```customUserName="user1"```
* my-postgres.yaml  
Append ```spec.customConfig: mypostgres-conf```.
Append
   ```
      - name: POSTGRES_MY_DB_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: myDbUserPassword
   ```

Could you kindly help me to resolve this issue?

[yamlfiles.zip](https://github.com/reactive-tech/kubegres/files/6375908/yamlfiles.zip)

**Comment by alex-arica** [comment]
Hello,

Thank you for your message. 

I run the YAML files that you attached in this ticket and when I connect to PostgreSql and I run the following command:

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 testdb    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres         +
           |          |          |            |            | postgres=CTc/postgres+
           |          |          |            |            | user1=CTc/postgres
(4 rows)


I can see the database "testdb"

What do you see when you run?
kubectl logs mypostgres-1-0

**Comment by t-kataym** [comment]
Thank you for your quick response and confirmation.

> What do you see when you run?
> kubectl logs mypostgres-1-0

The log says ```PostgreSQL Database directory appears to contain a database; Skipping initialization```.

I could not have removed the old volume completely when recreating Kube cluster.
(I uses minikube. Even if deleting Kube cluster, files still existed on [the host](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/).)
Now it works fine by removing these files.

Thank you so much for your support.
