### ISSUE TITLE
Kubegres 1.1 on minikube running but service mypostgres and mypostgres-replica don't assing external IP

### ISSUE THREAD

**Issue by PauloLaScience** [reactive-tech/kubegres#9]
Hi,
I deployed successfully on minikube version: v1.19.0
```
kubectl get all
NAME                 READY   STATUS    RESTARTS   AGE
pod/mypostgres-1-0   1/1     Running   0          24m
pod/mypostgres-2-0   1/1     Running   0          23m
pod/mypostgres-3-0   1/1     Running   0          22m

NAME                         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
service/kubernetes           ClusterIP   10.96.0.1    <none>        443/TCP    36m
service/mypostgres           ClusterIP   None         <none>        5432/TCP   23m
service/mypostgres-replica   ClusterIP   None         <none>        5432/TCP   22m

NAME                            READY   AGE
statefulset.apps/mypostgres-1   1/1     24m
statefulset.apps/mypostgres-2   1/1     23m
statefulset.apps/mypostgres-3   1/1     22m

```
But I can't access Postgres db:
```
○ → minikube service mypostgres
|-----------|------------|-------------|--------------|
| NAMESPACE |    NAME    | TARGET PORT |     URL      |
|-----------|------------|-------------|--------------|
| default   | mypostgres |             | No node port |
|-----------|------------|-------------|--------------|
😿  service default/mypostgres has no node port

```
```

kubectl get services 
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kubernetes           ClusterIP   10.96.0.1    <none>        443/TCP    46m
mypostgres           ClusterIP   None         <none>        5432/TCP   33m
mypostgres-replica   ClusterIP   None         <none>        5432/TCP   33m

```
Regards,
PaulemPG

**Comment by alex-arica** [comment]
Thank you for your message. By default, Kubegres creates services as headless cluster IP. It means the services are only accessible from an application running inside kubernetes cluster. Inside a container for example.

That behaviour is also more secure as by default in production we don't want our PostgreSql databases to be accessible from outside the cluster.

You can manually change that by editing the service resource and set its property to NodePort. 

Try this command:
kubectl edit svc/mypostgres

And change the property to:
spec:
   type: NodePort

You can remove this property:
spec:
   clusterIP: None

**Comment by PauloLaScience** [comment]
Hi 
I leave it as it is and in place I deploy a pgadmin pod via this site: [pgadmin pod](https://hub.kubeapps.com/charts/cetic/pgadmin)
Maybe a suggestion is to integrate to Kubegres a pgadmin pod like other operator
Thanks
Regards
PaulemPG

**Comment by alex-arica** [comment]
Thank you for your feedback. I took note about your suggestion. 

I understand it did not take you too long to install pgadmin pod and connect to Posgres pods managed by Kubegres. That's great, and it seems it is simple enough.

The architectural approach behind Kubegres is to only depend on the PostgreSql libraries which are shipped with the Docker official image of Postgres container. Consequently, we do not want to depend on third party tools and libraries outside the scope of that Postgres container.

We would like to keep Kubegres as much lightweight as possible. This approach has the advantage of letting people and companies to decide about which admin and monitoring tools they want. Many large companies have other preferences than pgadmin. For this reason, we prefer to not install any third party tools by default with Kubegres.

**Comment by PauloLaScience** [comment]
This is not an issue anymore and I understand point of vue about lightweight.
Regards
